/* Generated By:JJTree: Do not edit this line. ASTdeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTdeclaration extends SimpleNode {
    public ASTdeclaration(int id) {
        super(id);
    }
  
    public ASTdeclaration(GoDlangParser p, int id) {
        super(p, id);
    }
  
    public void translate(int indent) {
        if (type == Type.NUM) {
            output(indent, type.javaWord + " " + name + ";\n");
        } else {
            output(indent, type.javaWord + " " + name + " = new " + type.javaWord + "();\n");
        }
    }

    public void semanticCheck() throws ParseException, UnsupportedOperationException {
        Integer res = symb_types.putIfAbsent(name, (type.typeno << 16) + lineno); 
        if (res != null) {
            int resType = res.intValue() >> 16;
            int resLineno = res.intValue() - (resType << 16);
            throw new ParseException("Redefining " + name + "!\n"
                    + "Old definition at line " + resLineno
                    + ", new definition at line " + lineno + ".");
        }
    }
}
/* JavaCC - OriginalChecksum=fe8311e7dc442e815a9ab6fd376ceea2 (do not edit this line) */
