/* Generated By:JJTree: Do not edit this line. ASTparam.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam extends SimpleNode {
    public ASTparam(int id) {
        super(id);
    }
  
    public ASTparam(GoDlangParser p, int id) {
        super(p, id);
    }

    public void translate(int indent) {
        output(indent, type.javaWord + " " + name);
    }

    public void semanticCheck() throws ParseException {
        ASTaction act = (ASTaction) jjtGetParent();
        Integer res = act.params.putIfAbsent(name, (type.typeno << 16) + lineno);
        if (res != null) {
            int resType = res.intValue() >> 16;
            int resLineno = res.intValue() - (resType << 16);
            throw new ParseException("Redefining " + name + " in parameters of " + act.name + "!\n");
        }
    }
}
/* JavaCC - OriginalChecksum=b0b6795451b153a485b8c6a3b61d8167 (do not edit this line) */
