#!/usr/bin/env python

from funge.main import main
import os, sys

# try to enable JIT compilation. (50%-100% speed gain if enabled)
if not os.environ.get('PYFUNGE_NO_PSYCO'):
    try:
        import psyco
        #psyco.log()
        psyco.full()
    except ImportError:
        pass

try:
    sys.exit(main(sys.argv))
except KeyboardInterrupt:
    print >>sys.stderr, 'Interrupted.'
    sys.exit(1)

